---
version: 2
project_name: python-starter

before:
  hooks:
    - ./scripts/manpages.sh
    - ./scripts/completions.sh

snapshot:
  version_template: '{{ incpatch .Version }}-next'

builds:
  - id: wheel
    builder: uv
    buildmode: wheel
  - id: sdist
    builder: uv
    buildmode: sdist

universal_binaries:
  - replace: false

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

dockers_v2:
  - id: python-starter-py3.10
    images: &docker_images
      - 'toozej/python-starter'
      - 'ghcr.io/toozej/python-starter'
      - 'quay.io/toozej/python-starter'
    tags:
      - "v{{ .Version }}-py3.10"
      - "{{ .Version }}-py3.10"
      - "latest-py3.10"
    build_args:
      PYTHON_VERSION: "3.10"
    dockerfile: Dockerfile
    labels: &docker_labels
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/toozej/python-starter/main/README.md"
      "io.artifacthub.package.maintainers": "[{\"name\":\"toozej\"}]"
      "io.artifacthub.package.license": "GPLv3"
      "org.opencontainers.image.description": "python starter template"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.authors": "James Tooze https://github.com/toozej/"
      "org.opencontainers.image.documentation": "https://raw.githubusercontent.com/toozej/python-starter/main/README.md"
      "org.opencontainers.image.licenses": "GPL-3.0-only"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.vendor": "James Tooze"
    annotations: &docker_annotations
      "index,manifest:org.opencontainers.image.authors": "James Tooze https://github.com/toozej/"
      "index,manifest:org.opencontainers.image.created": "{{.Date}}"
      "index,manifest:org.opencontainers.image.description": "python starter template"
      "index,manifest:org.opencontainers.image.documentation": "https://raw.githubusercontent.com/toozej/python-starter/main/README.md"
      "index,manifest:org.opencontainers.image.licenses": "GPL-3.0-only"
      "index,manifest:org.opencontainers.image.revision": "{{.FullCommit}}"
      "index,manifest:org.opencontainers.image.source": "https://github.com/toozej/python-starter"
      "index,manifest:org.opencontainers.image.title": "{{.ProjectName}}"
      "index,manifest:org.opencontainers.image.vendor": "James Tooze"
      "index,manifest:org.opencontainers.image.version": "{{.Version}}"
    extra_files: &docker_extra_files
      - scripts/goreleaser_entrypoint.sh
      - pyproject.toml
      - uv.lock
      - python_starter/
      - tests/
      - README.md
  - id: python-starter-py3.11
    images: *docker_images
    tags:
      - "v{{ .Version }}-py3.11"
      - "{{ .Version }}-py3.11"
      - "latest-py3.11"
    build_args:
      PYTHON_VERSION: "3.11"
    dockerfile: Dockerfile
    labels: *docker_labels
    annotations: *docker_annotations
    extra_files: *docker_extra_files
  - id: python-starter-py3.12
    images: *docker_images
    tags:
      - "v{{ .Version }}-py3.12"
      - "{{ .Version }}-py3.12"
      - "latest-py3.12"
    build_args:
      PYTHON_VERSION: "3.12"
    dockerfile: Dockerfile
    labels: *docker_labels
    annotations: *docker_annotations
    extra_files: *docker_extra_files
  - id: python-starter-py3.13
    images: *docker_images
    tags:
      - "v{{ .Version }}-py3.13"
      - "{{ .Version }}-py3.13"
      - "latest-py3.13"
    build_args:
      PYTHON_VERSION: "3.13"
    dockerfile: Dockerfile
    labels: *docker_labels
    annotations: *docker_annotations
    extra_files: *docker_extra_files
  - id: python-starter-py3.14
    images: *docker_images
    tags:
      - "v{{ .Version }}-py3.14"
      - "{{ .Version }}-py3.14"
      - "latest-py3.14"
    build_args:
      PYTHON_VERSION: "3.14"
    dockerfile: Dockerfile
    labels: *docker_labels
    annotations: *docker_annotations
    extra_files: *docker_extra_files

archives:
  - name_template: >-
      "{{ .ProjectName }}_{{ .Version }}"
    files:
      - dist/*.whl
      - dist/*.tar.gz
      - README.md
      - LICENSE
      - manpages/*
      - completions/*

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    args:
      - 'sign-blob'
      - '--key=env://COSIGN_PRIVATE_KEY'
      - '--yes'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: all

docker_signs:
  - cmd: cosign
    artifacts: all
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    args:
      - 'sign'
      - '--key=env://COSIGN_PRIVATE_KEY'
      - '--yes'
      - '${artifact}'

milestones:
  - close: true

release:
  footer: |
    **Full Changelog**: https://github.com/toozej/python-starter/compare/{{ .PreviousTag }}...{{ .Tag }}
