---
version: 2
project_name: python-starter

before:
  hooks:
    - ./scripts/manpages.sh
    - ./scripts/completions.sh

snapshot:
  version_template: '{{ incpatch .Version }}-next'

builds:
  - id: wheel
    builder: uv
    buildmode: wheel
  - id: sdist
    builder: uv
    buildmode: sdist

universal_binaries:
  - replace: false

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

dockers_v2:
  - id: python-starter
    images:
      - 'toozej/python-starter'
      - 'ghcr.io/toozej/python-starter'
      - 'quay.io/toozej/python-starter'
    tags:
      - "v{{ .Version }}"
      - "{{ .Version }}"
      - "latest"
    dockerfile: Dockerfile
    labels:
      "io.artifacthub.package.readme-url": "https://raw.githubusercontent.com/toozej/python-starter/main/README.md"
      "io.artifacthub.package.maintainers": "[{\"name\":\"toozej\"}]"
      "io.artifacthub.package.license": "GPLv3"
      "org.opencontainers.image.description": "python starter template"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.authors": "James Tooze https://github.com/toozej/"
      "org.opencontainers.image.documentation": "https://raw.githubusercontent.com/toozej/python-starter/main/README.md"
      "org.opencontainers.image.licenses": "GPL-3.0-only"
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.vendor": "James Tooze"
    annotations:
      "index,manifest:org.opencontainers.image.authors": "James Tooze https://github.com/toozej/"
      "index,manifest:org.opencontainers.image.created": "{{.Date}}"
      "index,manifest:org.opencontainers.image.description": "python starter template"
      "index,manifest:org.opencontainers.image.documentation": "https://raw.githubusercontent.com/toozej/python-starter/main/README.md"
      "index,manifest:org.opencontainers.image.licenses": "GPL-3.0-only"
      "index,manifest:org.opencontainers.image.revision": "{{.FullCommit}}"
      "index,manifest:org.opencontainers.image.source": "https://github.com/toozej/python-starter"
      "index,manifest:org.opencontainers.image.title": "{{.ProjectName}}"
      "index,manifest:org.opencontainers.image.vendor": "James Tooze"
      "index,manifest:org.opencontainers.image.version": "{{.Version}}"
    extra_files:
      - scripts/goreleaser_entrypoint.sh

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - README.md
      - LICENSE
      - manpages/*
      - completions/*

homebrew_casks:
  - name: python-starter
    homepage: https://github.com/toozej/python-starter
    description: "python starter template"
    license: GPLv3
    repository:
      owner: toozej
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    manpages:
      - "manpages/python-starter.1.gz"
    completions:
      bash: "completions/python-starter.bash"
      zsh: "completions/python-starter.zsh"
      fish: "completions/python-starter.fish"
    url:
      verified: "github.com/toozej/python-starter/releases/download"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/python-starter"]
          end

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    args:
      - 'sign-blob'
      - '--key=env://COSIGN_PRIVATE_KEY'
      - '--yes'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: all

docker_signs:
  - cmd: cosign
    artifacts: all
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    args:
      - 'sign'
      - '--key=env://COSIGN_PRIVATE_KEY'
      - '--yes'
      - '${artifact}'

milestones:
  - close: true

release:
  footer: |
    **Full Changelog**: https://github.com/toozej/python-starter/compare/{{ .PreviousTag }}...{{ .Tag }}
